version: '3.8'
services:
  app:
    build: .
    container_name: mv_app
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor
    depends_on:
      - db
    env_file:
      - parameters.env
    networks:
      - mvnet

  web:
    image: nginx:stable
    container_name: mv_nginx
    ports:
      - "8083:80"
    volumes:
      - ./:/var/www/html:ro
      - ./deploy/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - mvnet

  db:
    image: mariadb:10.6
    container_name: mv_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=ecommerce
      - MYSQL_USER=ecommerce
      - MYSQL_PASSWORD=ecommerce
    volumes:
      - dbdata:/var/lib/mysql
      - ./docs/scripts/09_ecommerce.sql:/docker-entrypoint-initdb.d/09_ecommerce.sql:ro
    networks:
      - mvnet

volumes:
  dbdata:

networks:
  mvnet:
